dependencies:
- package: build
  version: 1.2.1
- package: click
  version: 8.1.7
- package: numpy
  version: 2.0.0
- package: opencv-python
  version: 4.10.0.84
- package: packaging
  version: '24.1'
- package: pip-tools
  version: 7.4.1
- package: pyproject_hooks
  version: 1.1.0
- package: PyQt5
  version: 5.15.10
- package: PyQt5-Qt5
  version: 5.15.14
- package: PyQt5-sip
  version: 12.13.0
- package: setuptools
  version: 70.3.0
- package: wheel
  version: 0.43.0
